#include <emscripten/bind.h>
#include <AR/ar.h>
#include <AR/config.h>
#include <AR/paramGL.h>
#include <AR/video.h>

using namespace emscripten;

EMSCRIPTEN_BINDINGS(artoolkit_constants) {
  // Pixel Formats
  constant("AR_PIXEL_FORMAT_RGB", AR_PIXEL_FORMAT_RGB + 0);
  constant("AR_PIXEL_FORMAT_BGR", AR_PIXEL_FORMAT_BGR + 0);
  constant("AR_PIXEL_FORMAT_RGBA", AR_PIXEL_FORMAT_RGBA + 0);
  constant("AR_PIXEL_FORMAT_BGRA", AR_PIXEL_FORMAT_BGRA + 0);
  constant("AR_PIXEL_FORMAT_MONO", AR_PIXEL_FORMAT_MONO + 0);
  constant("AR_PIXEL_FORMAT_420f", AR_PIXEL_FORMAT_420f + 0);
  constant("AR_PIXEL_FORMAT_420v", AR_PIXEL_FORMAT_420v + 0);
  // Detection Modes
  constant("AR_TEMPLATE_MATCHING_COLOR", AR_TEMPLATE_MATCHING_COLOR);
  constant("AR_TEMPLATE_MATCHING_MONO", AR_TEMPLATE_MATCHING_MONO);
  constant("AR_MATRIX_CODE_DETECTION", AR_MATRIX_CODE_DETECTION);
  constant("AR_TEMPLATE_MATCHING_COLOR_AND_MATRIX", AR_TEMPLATE_MATCHING_COLOR_AND_MATRIX);
  constant("AR_TEMPLATE_MATCHING_MONO_AND_MATRIX", AR_TEMPLATE_MATCHING_MONO_AND_MATRIX);
  constant("AR_DEFAULT_PATTERN_DETECTION_MODE", AR_DEFAULT_PATTERN_DETECTION_MODE);

    /* for arSetMatrixCodeType */
    constant("AR_MATRIX_CODE_3x3", AR_MATRIX_CODE_3x3 + 0);
    constant("AR_MATRIX_CODE_3x3_PARITY65", AR_MATRIX_CODE_3x3_PARITY65 + 0);
    constant("AR_MATRIX_CODE_3x3_HAMMING63", AR_MATRIX_CODE_3x3_HAMMING63 + 0);
    constant("AR_MATRIX_CODE_4x4", AR_MATRIX_CODE_4x4 + 0);
    constant("AR_MATRIX_CODE_4x4_BCH_13_9_3", AR_MATRIX_CODE_4x4_BCH_13_9_3 + 0);
    constant("AR_MATRIX_CODE_4x4_BCH_13_5_5", AR_MATRIX_CODE_4x4_BCH_13_5_5 + 0);
    constant("AR_MATRIX_CODE_5x5", AR_MATRIX_CODE_5x5 + 0);
    constant("AR_MATRIX_CODE_5x5_BCH_22_12_5", AR_MATRIX_CODE_5x5_BCH_22_12_5 + 0);
    constant("AR_MATRIX_CODE_5x5_BCH_22_7_7", AR_MATRIX_CODE_5x5_BCH_22_7_7 + 0);
    constant("AR_MATRIX_CODE_6x6", AR_MATRIX_CODE_6x6 + 0);
    constant("AR_MATRIX_CODE_GLOBAL_ID", AR_MATRIX_CODE_GLOBAL_ID + 0);
    constant("AR_MATRIX_CODE_TYPE_DEFAULT", AR_MATRIX_CODE_TYPE_DEFAULT + 0);


   /* errors */
    //constant("ERROR_MARKER_INDEX_OUT_OF_BOUNDS", arjs::artoolkit5::MARKER_INDEX_OUT_OF_BOUNDS);

    /* arDebug */
    constant("AR_DEBUG_DISABLE", AR_DEBUG_DISABLE);
    constant("AR_DEBUG_ENABLE", AR_DEBUG_ENABLE);
    constant("AR_DEFAULT_DEBUG_MODE", AR_DEFAULT_DEBUG_MODE);

    /* for arlabelingThresh */
    constant("AR_DEFAULT_LABELING_THRESH", AR_DEFAULT_LABELING_THRESH);

    /* for arImageProcMode */
    constant("AR_IMAGE_PROC_FRAME_IMAGE", AR_IMAGE_PROC_FRAME_IMAGE);
    constant("AR_IMAGE_PROC_FIELD_IMAGE", AR_IMAGE_PROC_FIELD_IMAGE);
    constant("AR_DEFAULT_IMAGE_PROC_MODE", AR_DEFAULT_IMAGE_PROC_MODE);

    /* for arGetTransMat */
    constant("AR_MAX_LOOP_COUNT", AR_MAX_LOOP_COUNT);
    constant("AR_LOOP_BREAK_THRESH", AR_LOOP_BREAK_THRESH);

    /* Enums */
    constant("AR_LOG_LEVEL_DEBUG", AR_LOG_LEVEL_DEBUG + 0);
    constant("AR_LOG_LEVEL_INFO", AR_LOG_LEVEL_INFO + 0);
    constant("AR_LOG_LEVEL_WARN", AR_LOG_LEVEL_WARN + 0);
    constant("AR_LOG_LEVEL_ERROR", AR_LOG_LEVEL_ERROR + 0);
    constant("AR_LOG_LEVEL_REL_INFO", AR_LOG_LEVEL_REL_INFO + 0);

    constant("AR_LABELING_THRESH_MODE_MANUAL", AR_LABELING_THRESH_MODE_MANUAL + 0);
    constant("AR_LABELING_THRESH_MODE_AUTO_MEDIAN", AR_LABELING_THRESH_MODE_AUTO_MEDIAN + 0);
    constant("AR_LABELING_THRESH_MODE_AUTO_OTSU", AR_LABELING_THRESH_MODE_AUTO_OTSU + 0);
    constant("AR_LABELING_THRESH_MODE_AUTO_ADAPTIVE", AR_LABELING_THRESH_MODE_AUTO_ADAPTIVE + 0);
    constant("AR_LABELING_THRESH_MODE_AUTO_BRACKETING", AR_LABELING_THRESH_MODE_AUTO_BRACKETING + 0);
    constant("AR_LABELING_THRESH_MODE_DEFAULT", AR_LABELING_THRESH_MODE_DEFAULT + 0);

    constant("AR_MARKER_INFO_CUTOFF_PHASE_NONE", AR_MARKER_INFO_CUTOFF_PHASE_NONE + 0);
    constant("AR_MARKER_INFO_CUTOFF_PHASE_PATTERN_EXTRACTION", AR_MARKER_INFO_CUTOFF_PHASE_PATTERN_EXTRACTION + 0);
    constant("AR_MARKER_INFO_CUTOFF_PHASE_MATCH_GENERIC", AR_MARKER_INFO_CUTOFF_PHASE_MATCH_GENERIC + 0);
    constant("AR_MARKER_INFO_CUTOFF_PHASE_MATCH_CONTRAST", AR_MARKER_INFO_CUTOFF_PHASE_MATCH_CONTRAST + 0);
    constant("AR_MARKER_INFO_CUTOFF_PHASE_MATCH_BARCODE_NOT_FOUND",
             AR_MARKER_INFO_CUTOFF_PHASE_MATCH_BARCODE_NOT_FOUND + 0);
    constant("AR_MARKER_INFO_CUTOFF_PHASE_MATCH_BARCODE_EDC_FAIL",
             AR_MARKER_INFO_CUTOFF_PHASE_MATCH_BARCODE_EDC_FAIL + 0);
    constant("AR_MARKER_INFO_CUTOFF_PHASE_MATCH_CONFIDENCE", AR_MARKER_INFO_CUTOFF_PHASE_MATCH_CONFIDENCE + 0);
    constant("AR_MARKER_INFO_CUTOFF_PHASE_POSE_ERROR", AR_MARKER_INFO_CUTOFF_PHASE_POSE_ERROR + 0);
    constant("AR_MARKER_INFO_CUTOFF_PHASE_POSE_ERROR_MULTI", AR_MARKER_INFO_CUTOFF_PHASE_POSE_ERROR_MULTI + 0);
    constant("AR_MARKER_INFO_CUTOFF_PHASE_HEURISTIC_TROUBLESOME_MATRIX_CODES",
             AR_MARKER_INFO_CUTOFF_PHASE_HEURISTIC_TROUBLESOME_MATRIX_CODES + 0);
}